<?php
//装饰者模式
interface Decorator{
    public function display();
}

class XiaoFang implements Decorator{
    private $name;

    public function __construct($name)
    {
        $this->name = $name;
    }

    public function display()
    {
        // TODO: Implement display() method.
        echo "我是".$this->name." 我出门了!!!".PHP_EOL;
    }

}

class Finery implements Decorator{
    private $component;

    public function __construct(Decorator $component)
    {
        $this->component = $component;
    }

    public function display()
    {
        // TODO: Implement display() method.
        $this->component->display();

    }
}

class Shoes extends Finery{
    public function display()
    {
        echo "穿上鞋子".PHP_EOL;
        parent::display(); // TODO: Change the autogenerated stub
    }
}

class Skirt extends Finery{
    public function display()
    {
        echo "穿上裙子".PHP_EOL;
        parent::display(); // TODO: Change the autogenerated stub
    }
}

class Fire extends Finery{
    public function display()
    {
        echo "出门前先整理头发".PHP_EOL;
        parent::display(); // TODO: Change the autogenerated stub
        echo "出门后再整理一次头发".PHP_EOL;
    }
}

$xiaofang =  new XiaoFang('小芳');
$shoes = new Shoes($xiaofang);
$skirt = new Skirt($shoes);
$fire = new Fire($skirt);
$fire->display();



?>